"""initial Migrate

Revision ID: 667e2bb82d9c
Revises: 
Create Date: 2022-01-30 23:22:19.838577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667e2bb82d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('sensor', 'humidity')
    op.drop_column('sensor', 'wind_speed')
    op.drop_column('sensor', 'temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('temperature', sa.INTEGER(), nullable=True))
    op.add_column('sensor', sa.Column('wind_speed', sa.INTEGER(), nullable=True))
    op.add_column('sensor', sa.Column('humidity', sa.INTEGER(), nullable=True))
    op.drop_table('weather')
    # ### end Alembic commands ###
